# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-03 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='reviewer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'manager_inheritance_from_future': True,
            },
        ),
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('reviewer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='users.reviewer')),
                # ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=300)),
                ('mobile', models.CharField(max_length=12)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'manager_inheritance_from_future': True,
            },
            bases=('users.reviewer',),
        ),
        migrations.CreateModel(
            name='Critics',
            fields=[
                ('reviewer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='users.reviewer')),
                # ('critic_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=50)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_critic', models.BooleanField(default=True)),
            ],
            options={
                'manager_inheritance_from_future': True,
            },
            bases=('users.reviewer',),
        ),
        migrations.AddField(
            model_name='reviewer',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False,  default=999999,null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_users.reviewer_set+', to='contenttypes.ContentType'),
        ),
    ]
