# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-25 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audience',
            name='dbpass',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
