# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-05 15:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewer',
            name='id',
        ),
        migrations.AddField(
            model_name='audience',
            name='user_id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='critics',
            name='critic_id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviewer',
            name='reviewer_id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='audience',
            name='reviewer_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='users.reviewer'),
        ),
        migrations.AlterField(
            model_name='critics',
            name='reviewer_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='users.reviewer'),
        ),
        migrations.AlterField(
            model_name='reviewer',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_users.reviewer_set+', to='contenttypes.ContentType'),
        ),
    ]
