# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-25 04:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190624_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='audience',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='audience',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
