# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-25 09:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190625_0902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audience',
            name='dbpass',
        ),
    ]
