# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-22 14:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190705_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audience',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='critics',
            name='is_critic',
        ),
    ]
