# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-29 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_critics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audience',
            name='password',
            field=models.CharField(max_length=300),
        ),
    ]
