# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-24 05:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=12)),
            ],
        ),
    ]
