# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-03 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('movies_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15, unique=True)),
                ('director', models.CharField(max_length=15)),
                ('writer', models.CharField(max_length=15)),
                ('music', models.CharField(max_length=30)),
                ('cast', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=300)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='movies.Movies')),
                ('reviewer', models.ManyToManyField(related_name='review', to='users.reviewer')),
            ],
        ),
    ]
