# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-22 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movies_movie_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='movie_poster',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
    ]
